### PR TITLE
some minor bug found, hopefuly my modifications are valid~

### PR DESCRIPTION
**Pull request by vanNul**
thank you for providing such a excellent opensource fastq preprocessor, I have studied your code recently and found s minor some minor bugs:
1, the adapter sequence should be the overlap part of external provided adapterseq and the fastq read seq? If so, I think my modification is reasonable, if not, I would appreciate your idea about this treating

2, during the estimation of read number of a fastq file, the left bytes shouldn't take the first read into account, so I think the divisor records should minus 1
check it here:

### CODE REVIEW

**Comment by sfchen** [comment]
Thanks, I will review it soon.

**Comment by sfchen** [comment]
Sorry, but after a careful review, I think both of your changes are incorrect, so I cannot merge them.

Your future contributions are still welcome.

**Comment by vanNul** [comment]
thank you, I realized where am I wrong now, when estimate the read number, after the first read is readed, in fact there have been more bytes red into the buffer  than that one read needed, so we minght just minus one read, the accurate amount is really so hard to calculate to my knowledge, but aftet minus - read, i test this function and found the results is still accurate for my tested fastq file, an I think this little offset will not affect the results if the fastq is large enough. anyway, keep it just like the original will not affect so much about the estimation as well.

**Comment by vanNul** [comment]
as the adapter sequence, I agree with your calculation now after some through thought, thank you for reviewing my misleading modifications very much.

**Pull request closed without merging**
